groups:

- name: alert.rules
  rules:
  - alert: Need_check!!!
    expr: up == 0
    for: 0m
    labels:
      severity: "critical"
    annotations:
      summary: "Server {{ $labels.instance }} down"
      description: "{{ $labels.job }} has been down for more than 1 minutes."