---
- name: Install Borg
  apt: 
    pkg:
    - python3-pexpect
    - python3-pip
    - borgbackup  
    state: present
    update_cache: yes

- name: Install pexpect python package
  ansible.builtin.pip:
    name: pexpect

- name: Create group borg
  group:
    name: "borg"
    state: present

- name: Add local backup user
  user:
    name: borg
    shell: /bin/bash
    groups: borg
    comment: Backup User Account

- name: Check if SSH key alredy exists
  stat:
    path: /home/borg/.ssh/authorized_keys
  register: result

- name: Setting up ssh keys
  block:    
    - name: Create ssh directory for borg
      file:
        path: /home/borg/.ssh
        state: directory
        owner: borg
        group: borg
        mode: 0700

    - name: Create ssh directory for borg
      file:
        path: /home/borg/.ssh/authorized_keys
        state: touch
        owner: borg
        group: borg
        mode: 0600

    - name: Generate an OpenSSH keypair with the default values (4096 bits, rsa)
      openssh_keypair:
        path: /home/borg/.ssh/id_rsa
        owner: borg
        group: borg

    - name: Enable pub key authentication in SSH
      lineinfile:
        path: "/etc/ssh/sshd_config"
        regexp: '^(.*)PubkeyAuthentication(.*)$'
        line: 'PubkeyAuthentication yes'
      
    - name: Copy files from remote to local
      fetch:
        src: /home/borg/.ssh/id_rsa.pub
        dest: /tmp/authorized_keys
        flat: yes

    - name: Restart SSH
      service:
        name: ssh
        state: restarted
  when: not result.stat.exists