---
- name: Set timezone to {{ tz_name }}
  community.general.timezone:
    name: '{{ tz_name }}'

- name: Install a list of packages
  apt:
    pkg:
    - vim
    - curl
    state: present
    update_cache: yes