---
serviceName: "prometheus"
groupId: "prometheus"
userId: "prometheus"
exec_command: "/usr/local/bin/prometheus --config.file=/etc/prometheus/prometheus.conf --storage.tsdb.path=/var/lib/prometheus/ --storage.tsdb.retention.time=2d --web.console.templates=/etc/prometheus/consoles --web.console.libraries=/etc/prometheus/console_libraries"
version: "2.51.1"