# - name: Install grafana
#   apt:
#     deb: https://dl.grafana.com/enterprise/release/grafana-enterprise_{{ version }}_amd64.deb
#     update_cache: yes

# - name: "Grafana configuration file copy"
#   template:
#     src: "grafana.conf.j2"
#     dest: /etc/grafana/grafana.ini
#   notify: Restart Grafana
- name: Install gnupg
  apt: 
    name: gnupg
    state: present 
    update_cache: yes

- name: Import Grafana Apt Key
  apt_key:
    url: https://packages.grafana.com/gpg.key
    state: present

- name: Add APT Repository
  apt_repository:
    repo: deb https://apt.grafana.com stable main
    state: present

- name: Install Grafana on Debian Family
  apt:
    name: grafana
    state: present  
    update_cache: yes

- name: "Grafana server started"
  service:
    name: grafana-server
    state: started
    enabled: yes