---
- name: Install gnupg2
  apt: 
    name: gnupg2
    state: present 
    update_cache: yes

- name: Import Grafana Apt Key
  apt_key:
    url: https://packages.grafana.com/gpg.key
    state: present

- name: Add APT Repository
  apt_repository:
    repo: deb https://apt.grafana.com stable main
    state: present

- name: Install Grafana
  apt:
    name: grafana
    state: present  
    update_cache: yes

- name: Grafana server started
  service:
    name: grafana-server
    state: started
    enabled: yes