---
- name: Ensure OpenSSL is installed
  apt:
    name: "{{ self_signed_ssl_openssl_package }}"
    update_cache: yes
    cache_valid_time: 86400

- name: Ensure directories exists for SSL certificate assets
  file:
    path: "{{ item.path }}"
    state: directory
    mode: "{{ item.mode }}"
    owner: "{{ self_signed_ssl_owner }}"
    group: "{{ self_signed_ssl_group }}"
  loop:
  - { path: "{{ self_signed_ssl_private_key_path }}",  mode: '0700' }
  - { path: "{{ self_signed_ssl_csr_path }}",  mode: '0755' }
  - { path: "{{ self_signed_ssl_certificate_path }}",  mode: '0755' }

- name: Generate OpenSSL private keys
  openssl_privatekey:
    path: "{{ self_signed_ssl_private_key_path }}/{{ item }}.pem"
  loop: "{{ self_signed_ssl_hosts }}"

- name: Generate OpenSSL CSR's
  openssl_csr:
    path: "{{ self_signed_ssl_csr_path }}/{{ item }}.csr"
    privatekey_path: "{{ self_signed_ssl_private_key_path }}/{{ item }}.pem"
    common_name: "{{ item }}"
  loop: "{{ self_signed_ssl_hosts }}"

- name: Generate self-signed OpenSSL certificates
  openssl_certificate:
    path: "{{ self_signed_ssl_certificate_path }}/{{ item }}.crt"
    privatekey_path: "{{ self_signed_ssl_private_key_path }}/{{ item }}.pem"
    csr_path: "{{ self_signed_ssl_csr_path }}/{{ item }}.csr"
    provider: selfsigned
  loop: "{{ self_signed_ssl_hosts }}"