global:
  resolve_timeout: 10s

route:
  group_by: ['alertname']
  group_wait: 3s
  receiver: 'telegram_bot'

receivers:
- name: 'telegram_bot'
  telegram_configs:
  - bot_token: '6984322955:AAGtq_0-1EESp6b6YzaCE3jUfMGbctdVbsY'
    api_url: 'https://api.telegram.org'
    chat_id: -1002007394446
    parse_mode: 'HTML'