---
- name: Update apt cache
  apt: 
    update_cache: yes
    cache_valid_time: 3600
  become: yes

- name: Install packets
  apt:
    name: "{{ item }}"
    state: present
  become: yes
  with_items:
    - nginx
    - php-fpm
    - php-mysql

- name: Start nginx
  become: yes
  service:
    name: nginx
    state: started

- name: Disable default pool
  command: mv /etc/php/7.4/fpm/pool.d/www.conf /etc/php/7.4/fpm/www.disabled creates=/etc/php/7.4/fpm/www.disabled
  notify: restart php-fpm

- name: Update PHP-fpm conf
  copy: 
    src: "files/php_wordpress.conf"
    dest: "/etc/php/7.4/fpm/pool.d/php_wordpress.conf"
    owner: www-data
    group: www-data
    mode: 0644
  notify: restart php-fpm
  become: yes

- name: Add nginx settings
  copy:
    src: "files/nginx.conf"
    dest: "/etc/nginx/nginx.conf"
    owner: www-data
    group: www-data
    mode: 0644
  notify: restart nginx
  become: yes

- name: Create webroot
  file:
    state: directory
    path: "/srv/www/"
    owner: root
    group: root
    mode: 0755
  become: yes

- name: Check if WordPress directory exists in /srv/www
  stat:
    path: "/srv/www/example.com"
  register: check_path

- name: Update nginx confs for WordPress + PHP
  copy: 
    src: "files/wordpress.conf"
    dest: "/etc/nginx/sites-available/wordpress"
    owner: www-data
    group: www-data
    mode: 0644
  become: yes

- name: Delete content & directory
  file:
    state: absent
    path: /etc/nginx/sites-enabled/default

- name: Enable wordpress site
  file: 
    src: "/etc/nginx/sites-available/wordpress"
    dest: "/etc/nginx/sites-enabled/wordpress"
    owner: www-data
    group: www-data
    state: link
  notify: restart nginx
  become: yes

- name: Setup php-fpm
  replace:
    dest: "/etc/php/7.4/fpm/php.ini"
    regexp: "(;cgi.fix_pathinfo=1)"
    replace: "cgi.fix_pathinfo=0"
  notify: restart nginx
  become: yes

- name: Download WordPress
  get_url:
    url: "https://wordpress.org/wordpress-{{ wp_version }}.tar.gz"
    dest: "/tmp/wordpress-{{ wp_version }}.tar.gz"
    checksum: "sha1:{{ wp_sha1sum }}"
  become: yes
  when: not check_path.stat.exists

- name: Extract WordPress
  unarchive:
    src: "/tmp/wordpress-{{ wp_version }}.tar.gz"
    dest: "/tmp"
    owner: www-data
    group: 
    copy: no
  become: yes
  when: not check_path.stat.exists

- name: Move WordPress install files
  command: "mv /tmp/wordpress /srv/www/example.com"
  become: yes
  when: not check_path.stat.exists

- name: Fetch random salts for WordPress config
  local_action: command curl https://api.wordpress.org/secret-key/1.1/salt/
  register: "wp_salt"
  become: no

- name: Add wp-config
  copy:
    src: "files/wp-config.php"
    dest: "/srv/www/example.com/wp-config.php"
    owner: www-data
    group: www-data
    mode: 0755
  become: yes

- name: Update WordPress config file
  lineinfile:
    dest: "/srv/www/example.com/wp-config.php"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - {'regexp': "define\\('DB_NAME', '(.)+'\\);", 'line': "define('DB_NAME', '{{wp_db_name}}');"}
    - {'regexp': "define\\('DB_USER', '(.)+'\\);", 'line': "define('DB_USER', '{{wp_db_user}}');"}
    - {'regexp': "define\\('DB_PASSWORD', '(.)+'\\);", 'line': "define('DB_PASSWORD', '{{wp_db_password}}');"}
  become: yes