---
- name: Adding Elasticsearch repo
  apt_repository:
    repo: deb [trusted=yes] https://mirror.yandex.ru/mirrors/elastic/8/ stable main
    state: present

- name: Install Elasticsearch
  apt: 
    pkg:
    - default-jdk
    - elasticsearch
    state: present
    update_cache: yes

- name: Update Elasticsearch Configuration File
  lineinfile:
    path: /etc/elasticsearch/elasticsearch.yml
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  loop:
    - { regexp: '^network\.host:', line: 'network.host: {{ network_host }}' }
    - { regexp: '^http\.port:', line: 'http.port: {{ http_port }}' }

- name: Enable and start Elasticsearch service
  service:
    name: elasticsearch
    state: started
    enabled: yes

- name: Run Elasticsearch Reset Password Command
  command: /usr/share/elasticsearch/bin/elasticsearch-reset-password auto -u elastic
  args:
    stdin: "y"  
  register: reset_password_output
  
# Set var with password
- set_fact:
    elastic_pass: "{{ reset_password_output.stdout_lines[-1] | regex_replace('^New value: (.*)$', '\\1') }}"