---
- hosts: web
  become: yes
  roles:
        - common
        - web
        - router
# restore
        #- web_back
- hosts: 
        - mysql
        - replica
  become: yes
  roles:
        - common
        - mysql
# restore
        #- mysql_back

- hosts: prometheus
  become: yes
  roles:
        - common
        - prometheus
        - grafana
        - alertmanager 

- hosts: elk
  become: yes
  roles:
        - common
        - elk
        - kibana
        - logstash

- hosts: all
  become: yes
  roles:
        - filebeat
        - node_exporter
        - backup
        #- routes