---
- name: Check if file exists
  stat:
    path: "/usr/local/bin/alertmanager"
  register: result

- name: Creating alertmanager user group
  group: name="{{groupId}}"
  become: true

- name: Creating alertmanager user
  user:
    name: "{{userId}}"
    group: "{{groupId}}"
    system: yes
    shell: "/sbin/nologin"
    comment: "{{userId}} nologin User"
    createhome: "no"
    state: present
  
- name: Download packets
  block: 
    - name: Download alertmanager
      unarchive:
        src: "https://github.com/prometheus/alertmanager/releases/download/v{{ version }}/alertmanager-{{ version }}.linux-amd64.tar.gz"
        dest: /tmp/
        remote_src: yes
      #when: not result.stat.exists

    - name: Copy files from remote to local store
      fetch:
        src: "/tmp/alertmanager-{{ version }}.linux-amd64/alertmanager"
        dest: "/tmp/alertmanager-{{ version }}.linux-amd64/alertmanager"
        flat: yes
    #   when: not result.stat.exists

    - name: Copy alertmanager executable to bin
      copy:
        src: "/tmp/alertmanager-{{ version }}.linux-amd64/alertmanager"
        dest: "/usr/local/bin/alertmanager"
        owner: "{{userId}}"
        group: "{{groupId}}"
        #remote_src: yes
        mode: 0755
  when: not result.stat.exists

- name: Creates data directory
  file: 
    path: "/var/lib/alertmanager/"
    state: directory
    owner: "{{userId}}"
    group: "{{groupId}}"
    mode: 0755

- name: Creates config directory
  file: 
    path: "/etc/alertmanager/"
    state: directory
    owner: "{{userId}}"
    group: "{{groupId}}"
    mode: 0755

- name: Copy config file
  copy:
    src: "files/alertmanager.yml"
    dest: /etc/alertmanager/alertmanager.yml

- name: Copy systemd init file
  template:
    src: init.service.j2
    dest: /etc/systemd/system/alertmanager.service
  notify: systemd_reload

- name: Start alertmanager service
  service:
    name: alertmanager
    state: started
    enabled: yes

- name: Check if alertmanager is accessible
  uri:
    url: http://localhost:9093
    method: GET
    status_code: 200