---
- name: Install Kibana with apt
  apt:
   name: kibana
   state: present
   update_cache: yes

- name: Update Elasticsearch Configuration File
  lineinfile:
    path: /etc/kibana/kibana.yml
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  loop:
    - { regexp: '^server\.host:', line: 'server.host: "{{ server_host }}"' }

- name: Run Elasticsearch Create Enrollment Token Command
  shell: /usr/share/elasticsearch/bin/elasticsearch-create-enrollment-token -s kibana
  register: token_response

- name: Extract Token from Response
  set_fact:
    enrollment_token: "{{ token_response.stdout }}"

- name: Run Kibana Enrollment Token Command
  shell: /usr/share/kibana/bin/kibana-setup --enrollment-token {{ enrollment_token }}
  args:
    stdin: "y"

- name: Enable and start kibana service
  service:
    name: kibana
    state: started
    enabled: yes