global:
  resolve_timeout: 10s

route:
  group_by: ['alertname']
  group_wait: 3s
  receiver: 'telegram_bot'

receivers:
- name: 'telegram_bot'
  telegram_configs:
  - bot_token: 'enter Your token'
    api_url: 'https://api.telegram.org'
    chat_id: -enter Your chat Id
    parse_mode: 'HTML'
